"use client";

import { useMemo, useState } from "react";
import type { ReactNode } from "react";
import { AiBadge, Badge } from "@/components/ui/Badge";
import { InfoTip } from "@/components/ui/InfoTip";
import { Panel, PanelHeader } from "@/components/ui/Panel";
import { Toggle } from "@/components/ui/Toggle";
import type { ContentAnalysis } from "@/data/analysis";
import type { Accommodation, Content, ShotItem } from "@/data/types";

interface Row {
  key: string;
  label: string;
  minCount: number;
  current: number;
  autoGenerated: boolean;
  derivedFrom: string;
  isRequired: boolean;
}

export function ShootTab({
  content,
  acc,
  analysis,
  preDepartureCheck,
  onPreDepartureCheckChange,
}: {
  content: Content;
  acc: Accommodation;
  analysis: ContentAnalysis;
  preDepartureCheck: boolean;
  onPreDepartureCheckChange: (next: boolean) => void;
}) {
  const [excluded, setExcluded] = useState<string[]>(analysis.excludedShotLabels);
  const [extra, setExtra] = useState<ShotItem[]>([]);
  const [adding, setAdding] = useState(false);
  const [draftLabel, setDraftLabel] = useState("");
  const [draftCount, setDraftCount] = useState("2");

  const rows: Row[] = useMemo(() => {
    const base = [...analysis.shotList, ...extra].map((s) => ({
      key: s.id,
      label: s.label,
      minCount: s.minCount,
      current: analysis.shotCounts[s.label] ?? 0,
      autoGenerated: s.autoGenerated,
      derivedFrom: s.derivedFrom,
      isRequired: s.isRequired,
    }));
    if (!preDepartureCheck) return base;
    // 현장 모드에서는 아직 못 채운 항목이 위로 온다. 현장에서 확인할 건 그것뿐이다.
    return [...base].sort((a, b) => {
      const am = a.current >= a.minCount ? 1 : 0;
      const bm = b.current >= b.minCount ? 1 : 0;
      return am - bm;
    });
  }, [analysis, extra, preDepartureCheck]);

  const active = rows.filter((r) => !excluded.includes(r.label) && r.isRequired);
  const met = active.filter((r) => r.current >= r.minCount).length;

  const addItem = () => {
    const label = draftLabel.trim();
    const n = Number(draftCount);
    if (!label || !Number.isFinite(n) || n <= 0) return;
    setExtra((prev) => [
      ...prev,
      {
        id: `${acc.id}-manual-${prev.length + 1}`,
        facilityId: "manual",
        label,
        minCount: n,
        isRequired: true,
        autoGenerated: false,
        derivedFrom: "이 촬영 건만의 예외 (직접 추가)",
      },
    ]);
    setDraftLabel("");
    setDraftCount("2");
    setAdding(false);
  };

  return (
    <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_300px]">
      <div className="space-y-4">
        <Panel>
          <PanelHeader
            title="필수 컷 체크리스트"
            description="시설 정보에서 자동 생성됩니다. 항목은 전부 사진만 보고 판정할 수 있는 공간 유형입니다."
            right={
              <>
                <Badge variant="outline">
                  <span className="tnum">
                    {met}/{active.length}
                  </span>
                  {" 충족"}
                </Badge>
                <Badge variant="neutral">
                  자동 생성됨
                  <InfoTip align="right">
                    AI가 아닙니다. 숙소의 시설 정보를 규칙으로 연결해 만든 목록입니다.
                    항목은 사진만 보고 판정 가능한 공간 유형으로 제한했습니다.
                  </InfoTip>
                </Badge>
              </>
            }
          />

          {preDepartureCheck ? (
            <div className="border-b border-line bg-ai-bg px-4 py-2.5">
              <p className="text-body font-semibold text-ai">
                철수 전 확인 · 미충족 항목이 위로 정렬됩니다
              </p>
              <p className="mt-1 text-badge leading-[16px] text-fg-muted">
                아직 못 채운 컷만 위에 모아 둡니다. 현장에서 볼 건 그것뿐입니다.
              </p>
            </div>
          ) : null}

          <ul className="divide-y divide-line">
            {rows.map((row) => {
              const isExcluded = excluded.includes(row.label);
              const ok = row.current >= row.minCount;
              return (
                <li
                  key={row.key}
                  className={`flex items-center gap-3 px-4 ${
                    preDepartureCheck ? "py-3" : "py-2"
                  } ${isExcluded ? "bg-surface/60" : ""}`}
                >
                  <span
                    aria-hidden
                    className={`flex h-4 w-4 shrink-0 items-center justify-center rounded-box border text-[10px] leading-none ${
                      isExcluded
                        ? "border-line text-fg-subtle"
                        : ok
                          ? "border-success/30 bg-[#EDF4F2] text-success"
                          : "border-danger/30 bg-[#FBEBEB] text-danger"
                    }`}
                  >
                    {isExcluded ? "–" : ok ? "✓" : "✗"}
                  </span>

                  <div className="min-w-0 flex-1">
                    <div className="flex flex-wrap items-center gap-1.5">
                      <span
                        className={`text-body font-medium ${
                          isExcluded ? "text-fg-subtle line-through" : "text-fg"
                        }`}
                      >
                        {row.label}
                      </span>
                      {!row.isRequired ? <Badge variant="neutral">권장</Badge> : null}
                      {!row.autoGenerated ? (
                        <Badge variant="neutral">직접 추가</Badge>
                      ) : null}
                    </div>
                    <p className="mt-px text-badge text-fg-subtle">{row.derivedFrom}</p>
                  </div>

                  <span
                    className={`tnum shrink-0 text-body ${
                      isExcluded
                        ? "text-fg-subtle"
                        : ok
                          ? "text-fg-muted"
                          : "font-medium text-danger"
                    }`}
                  >
                    {row.current} / {row.minCount}
                  </span>

                  <button
                    type="button"
                    onClick={() =>
                      setExcluded((prev) =>
                        isExcluded
                          ? prev.filter((l) => l !== row.label)
                          : [...prev, row.label],
                      )
                    }
                    className="shrink-0 rounded-box border border-line px-1.5 py-0.5 text-badge text-fg-muted transition-colors hover:border-line-strong hover:text-fg"
                  >
                    {isExcluded ? "복구" : "제외"}
                  </button>
                </li>
              );
            })}
          </ul>

          <div className="border-t border-line px-4 py-2">
            {adding ? (
              <div className="flex flex-wrap items-center gap-2">
                <input
                  autoFocus
                  value={draftLabel}
                  onChange={(e) => setDraftLabel(e.target.value)}
                  placeholder="항목명 (예: 루프탑 스파)"
                  className="min-w-0 flex-1 rounded-box border border-line-strong px-2 py-1 text-body outline-none focus:border-fg-subtle"
                />
                <input
                  value={draftCount}
                  onChange={(e) => setDraftCount(e.target.value)}
                  inputMode="numeric"
                  aria-label="필요 장수"
                  className="tnum w-16 rounded-box border border-line-strong px-2 py-1 text-body outline-none focus:border-fg-subtle"
                />
                <button
                  type="button"
                  onClick={addItem}
                  className="rounded-box border border-line-strong bg-surface px-2 py-1 text-body font-medium text-fg"
                >
                  추가
                </button>
                <button
                  type="button"
                  onClick={() => setAdding(false)}
                  className="rounded-box px-2 py-1 text-body text-fg-muted"
                >
                  취소
                </button>
              </div>
            ) : (
              <button
                type="button"
                onClick={() => setAdding(true)}
                className="text-body text-fg-muted transition-colors hover:text-fg"
              >
                + 항목 추가
              </button>
            )}
          </div>
        </Panel>
      </div>

      <div className="space-y-4">
        <Panel>
          <PanelHeader title="촬영 정보" />
          <dl className="divide-y divide-line text-body">
            <Field label="숙소" value={acc.name} />
            <Field label="유형" value={acc.type} />
            <Field label="주소" value={acc.address} />
            <Field label="촬영일" value={content.shootDate} />
            <Field label="작가" value={content.photographer} />
            <Field
              label="재촬영"
              value={
                content.reshootCount > 0 ? (
                  <span className="text-danger">{content.reshootCount}회 발생</span>
                ) : (
                  "없음"
                )
              }
            />
          </dl>
        </Panel>

        <Panel>
          <div className="flex items-center justify-between gap-3 border-b border-line-strong bg-surface px-4 py-2.5">
            <div>
              <h2 className="text-section font-semibold text-fg">철수 전 확인</h2>
              <p className="mt-0.5 text-badge text-fg-muted">
                누락을 아는 시점을 5분 앞으로
              </p>
            </div>
            <Toggle
              id="pre-departure-check"
              label="철수 전 확인"
              checked={preDepartureCheck}
              onChange={onPreDepartureCheckChange}
            />
          </div>

          <div className="space-y-3 p-4">
            <ol className="space-y-1.5 text-body text-fg-muted">
              <Step n={1}>촬영이 끝나면 카드에서 JPG만 복사합니다 (약 4GB)</Step>
              <Step n={2}>업로드하면 라벨링과 누락 대조가 5분 안에 끝납니다</Step>
              <Step n={3}>빠진 컷만 다시 찍고 철수합니다</Step>
            </ol>

            <div className="rounded-box border border-line bg-surface p-2.5">
              <p className="text-badge leading-[16px] text-fg-muted">
                지금은 복귀 후에 올리고, 누락은 며칠 뒤 편집 단계에서 드러납니다. 그때는
                촬영팀이 철수한 뒤라 재방문 협의부터 다시 해야 합니다. 바꾸는 건 그
                <span className="text-fg"> 확인 시점 하나</span>입니다.
              </p>
            </div>

            {/* 검증 안 된 전제는 전제라고 적는다 */}
            <div className="rounded-box border border-warn/30 bg-[#FBF0E2] p-2.5">
              <p className="text-badge font-semibold text-warn">확인이 필요한 전제</p>
              <p className="mt-1 text-badge leading-[16px] text-fg-muted">
                현장에 업로드 가능한 네트워크가 있어야 하고, 촬영자가 철수 전 5분을 쓸
                수 있어야 합니다. 두 조건이 안 되면 이 기능은 복귀 후 검수용으로
                동작합니다. 그래도 편집 단계보다는 며칠 빠릅니다.
              </p>
            </div>

            <div className="flex items-center gap-2">
              <AiBadge label="라벨링 · 누락 탐지 (모의)" />
            </div>
          </div>
        </Panel>
      </div>
    </div>
  );
}

function Step({ n, children }: { n: number; children: ReactNode }) {
  return (
    <li className="flex gap-2">
      <span className="tnum mt-0.5 flex h-4 w-4 shrink-0 items-center justify-center rounded-full bg-ai text-[10px] leading-none font-semibold text-white">
        {n}
      </span>
      <span className="leading-[19px]">{children}</span>
    </li>
  );
}

function Field({ label, value }: { label: string; value: ReactNode }) {
  return (
    <div className="flex gap-3 px-4 py-2">
      <dt className="w-16 shrink-0 text-fg-subtle">{label}</dt>
      <dd className="min-w-0 flex-1 text-fg">{value}</dd>
    </div>
  );
}
