"use client";

import { useMemo, useState } from "react";
import type { ReactNode } from "react";
import { AiBadge, Badge } from "@/components/ui/Badge";
import { InfoTip } from "@/components/ui/InfoTip";
import { Panel, PanelHeader } from "@/components/ui/Panel";
import { Toggle } from "@/components/ui/Toggle";
import type { ContentAnalysis } from "@/data/analysis";
import type { Accommodation, Content, ShotItem } from "@/data/types";

interface Row {
  key: string;
  label: string;
  minCount: number;
  current: number;
  autoGenerated: boolean;
  derivedFrom: string;
  isRequired: boolean;
}

export function ShootTab({
  content,
  acc,
  analysis,
  fieldMode,
  onFieldModeChange,
}: {
  content: Content;
  acc: Accommodation;
  analysis: ContentAnalysis;
  fieldMode: boolean;
  onFieldModeChange: (next: boolean) => void;
}) {
  const [excluded, setExcluded] = useState<string[]>(analysis.excludedShotLabels);
  const [extra, setExtra] = useState<ShotItem[]>([]);
  const [adding, setAdding] = useState(false);
  const [draftLabel, setDraftLabel] = useState("");
  const [draftCount, setDraftCount] = useState("2");

  const rows: Row[] = useMemo(() => {
    const base = [...analysis.shotList, ...extra].map((s) => ({
      key: s.id,
      label: s.label,
      minCount: s.minCount,
      current: analysis.shotCounts[s.label] ?? 0,
      autoGenerated: s.autoGenerated,
      derivedFrom: s.derivedFrom,
      isRequired: s.isRequired,
    }));
    if (!fieldMode) return base;
    // 현장 모드에서는 아직 못 채운 항목이 위로 온다. 현장에서 확인할 건 그것뿐이다.
    return [...base].sort((a, b) => {
      const am = a.current >= a.minCount ? 1 : 0;
      const bm = b.current >= b.minCount ? 1 : 0;
      return am - bm;
    });
  }, [analysis, extra, fieldMode]);

  const active = rows.filter((r) => !excluded.includes(r.label) && r.isRequired);
  const met = active.filter((r) => r.current >= r.minCount).length;

  const addItem = () => {
    const label = draftLabel.trim();
    const n = Number(draftCount);
    if (!label || !Number.isFinite(n) || n <= 0) return;
    setExtra((prev) => [
      ...prev,
      {
        id: `${acc.id}-manual-${prev.length + 1}`,
        facilityId: "manual",
        label,
        minCount: n,
        isRequired: true,
        autoGenerated: false,
        derivedFrom: "이 촬영 건만의 예외 (직접 추가)",
      },
    ]);
    setDraftLabel("");
    setDraftCount("2");
    setAdding(false);
  };

  return (
    <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_300px]">
      <div className="space-y-4">
        <Panel>
          <PanelHeader
            title="필수 컷 체크리스트"
            description="시설 정보에서 자동 생성됩니다. 항목은 전부 사진만 보고 판정할 수 있는 공간 유형입니다."
            right={
              <>
                <Badge variant="outline">
                  <span className="tnum">
                    {met}/{active.length}
                  </span>
                  {" 충족"}
                </Badge>
                <Badge variant="neutral">
                  자동 생성됨
                  <InfoTip align="right">
                    AI가 아닙니다. 숙소 등록 시 입력한 시설 정보를 규칙으로 연결해 만든
                    목록입니다. 항목 이름은 사진만 보고 판정 가능한 공간 유형으로
                    제한했습니다. 객실 등급이나 번호는 이미지에 근거가 없어 넣지
                    않았습니다.
                  </InfoTip>
                </Badge>
              </>
            }
          />

          {fieldMode ? (
            <div className="border-b border-line bg-ai-bg px-4 py-2.5">
              <p className="text-body font-medium text-ai">
                현장 모드 · 미충족 항목이 위로 정렬됩니다
              </p>
              <p className="mt-1 text-badge leading-[16px] text-fg-muted">
                촬영 중 프리뷰(JPG)만 먼저 올려 누락을 현장에서 확인합니다. 원본(RAW)은
                복귀 후 업로드됩니다. 편집 단계에서 누락을 발견하면 촬영팀은 이미
                철수한 뒤입니다.
              </p>
            </div>
          ) : null}

          <ul className="divide-y divide-line">
            {rows.map((row) => {
              const isExcluded = excluded.includes(row.label);
              const ok = row.current >= row.minCount;
              return (
                <li
                  key={row.key}
                  className={`flex items-center gap-3 px-4 ${
                    fieldMode ? "py-3" : "py-2"
                  } ${isExcluded ? "bg-surface/60" : ""}`}
                >
                  <span
                    aria-hidden
                    className={`flex h-4 w-4 shrink-0 items-center justify-center rounded-box border text-[10px] leading-none ${
                      isExcluded
                        ? "border-line text-fg-subtle"
                        : ok
                          ? "border-success/30 bg-[#EDF4F2] text-success"
                          : "border-danger/30 bg-[#FBEBEB] text-danger"
                    }`}
                  >
                    {isExcluded ? "–" : ok ? "✓" : "✗"}
                  </span>

                  <div className="min-w-0 flex-1">
                    <div className="flex flex-wrap items-center gap-1.5">
                      <span
                        className={`text-body font-medium ${
                          isExcluded ? "text-fg-subtle line-through" : "text-fg"
                        }`}
                      >
                        {row.label}
                      </span>
                      {!row.isRequired ? <Badge variant="neutral">권장</Badge> : null}
                      {!row.autoGenerated ? (
                        <Badge variant="neutral">직접 추가</Badge>
                      ) : null}
                    </div>
                    <p className="mt-px text-badge text-fg-subtle">{row.derivedFrom}</p>
                  </div>

                  <span
                    className={`tnum shrink-0 text-body ${
                      isExcluded
                        ? "text-fg-subtle"
                        : ok
                          ? "text-fg-muted"
                          : "font-medium text-danger"
                    }`}
                  >
                    {row.current} / {row.minCount}
                  </span>

                  <button
                    type="button"
                    onClick={() =>
                      setExcluded((prev) =>
                        isExcluded
                          ? prev.filter((l) => l !== row.label)
                          : [...prev, row.label],
                      )
                    }
                    className="shrink-0 rounded-box border border-line px-1.5 py-0.5 text-badge text-fg-muted transition-colors hover:border-line-strong hover:text-fg"
                  >
                    {isExcluded ? "복구" : "제외"}
                  </button>
                </li>
              );
            })}
          </ul>

          <div className="border-t border-line px-4 py-2">
            {adding ? (
              <div className="flex flex-wrap items-center gap-2">
                <input
                  autoFocus
                  value={draftLabel}
                  onChange={(e) => setDraftLabel(e.target.value)}
                  placeholder="항목명 (예: 루프탑 스파)"
                  className="min-w-0 flex-1 rounded-box border border-line-strong px-2 py-1 text-body outline-none focus:border-fg-subtle"
                />
                <input
                  value={draftCount}
                  onChange={(e) => setDraftCount(e.target.value)}
                  inputMode="numeric"
                  aria-label="필요 장수"
                  className="tnum w-16 rounded-box border border-line-strong px-2 py-1 text-body outline-none focus:border-fg-subtle"
                />
                <button
                  type="button"
                  onClick={addItem}
                  className="rounded-box border border-line-strong bg-surface px-2 py-1 text-body font-medium text-fg"
                >
                  추가
                </button>
                <button
                  type="button"
                  onClick={() => setAdding(false)}
                  className="rounded-box px-2 py-1 text-body text-fg-muted"
                >
                  취소
                </button>
              </div>
            ) : (
              <button
                type="button"
                onClick={() => setAdding(true)}
                className="text-body text-fg-muted transition-colors hover:text-fg"
              >
                + 항목 추가
              </button>
            )}
          </div>
        </Panel>
      </div>

      <div className="space-y-4">
        <Panel>
          <PanelHeader title="촬영 정보" />
          <dl className="divide-y divide-line text-body">
            <Field label="숙소" value={acc.name} />
            <Field label="유형" value={acc.type} />
            <Field label="주소" value={acc.address} />
            <Field label="촬영일" value={content.shootDate} />
            <Field label="작가" value={content.photographer} />
            <Field
              label="재촬영"
              value={
                content.reshootCount > 0 ? (
                  <span className="text-danger">{content.reshootCount}회 발생</span>
                ) : (
                  "없음"
                )
              }
            />
          </dl>
        </Panel>

        <Panel className="border-ai/25">
          <div className="flex items-center justify-between gap-3 border-b border-line px-4 py-2.5">
            <div>
              <h2 className="text-section font-semibold text-fg">현장 모드</h2>
              <p className="mt-0.5 text-badge text-fg-subtle">
                촬영 중 누락을 현장에서 잡는다
              </p>
            </div>
            <Toggle
              id="field-mode"
              label="현장 모드"
              checked={fieldMode}
              onChange={onFieldModeChange}
            />
          </div>
          <div className="space-y-2 p-4">
            <p className="text-body leading-[19px] text-fg-muted">
              프리뷰(JPG)만 먼저 업로드해 라벨링과 누락 탐지를 현장에서 돌립니다. 원본
              RAW는 복귀 후 유선으로 올립니다.
            </p>
            <div className="rounded-box bg-surface p-2.5">
              <p className="text-badge leading-[16px] text-fg-muted">
                같은 AI 기능이라도 사후 검수용이면{" "}
                <span className="text-fg">재촬영을 빨리 아는 것</span>이고, 현장용이면{" "}
                <span className="text-fg">재촬영이 아예 안 생기는 것</span>입니다.
              </p>
            </div>
            <div className="flex items-center gap-2 pt-1">
              <AiBadge label="라벨링 · 누락 탐지 (모의)" />
            </div>
          </div>
        </Panel>
      </div>
    </div>
  );
}

function Field({ label, value }: { label: string; value: ReactNode }) {
  return (
    <div className="flex gap-3 px-4 py-2">
      <dt className="w-16 shrink-0 text-fg-subtle">{label}</dt>
      <dd className="min-w-0 flex-1 text-fg">{value}</dd>
    </div>
  );
}
