import type { Accommodation, Facilities, ShotItem } from "./types";

export const ACCOMMODATIONS: Accommodation[] = [
  {
    id: "acc-01",
    name: "제주 애월 오션뷰 풀빌라",
    type: "풀빌라",
    address: "제주 제주시 애월읍 애월해안로 621",
    region: "제주",
    facilities: { roomTypes: 3, pool: true, breakfast: true, bbq: true, pet: false, spa: true, outdoor: true },
  },
  {
    id: "acc-02",
    name: "강릉 안목해변 스테이",
    type: "펜션",
    address: "강원 강릉시 창해로14번길 20",
    region: "강릉",
    facilities: { roomTypes: 2, pool: false, breakfast: true, bbq: true, pet: true, spa: false, outdoor: true },
  },
  {
    id: "acc-03",
    name: "가평 청평호 글램핑파크",
    type: "글램핑",
    address: "경기 가평군 청평면 호반로 1035",
    region: "가평",
    facilities: { roomTypes: 2, pool: true, breakfast: false, bbq: true, pet: true, spa: false, outdoor: true },
  },
  {
    id: "acc-04",
    name: "여수 돌산 오션스테이",
    type: "독채",
    address: "전남 여수시 돌산읍 돌산로 3218",
    region: "여수",
    facilities: { roomTypes: 1, pool: false, breakfast: false, bbq: true, pet: false, spa: false, outdoor: true },
  },
  {
    id: "acc-05",
    name: "속초 설악뷰 호텔",
    type: "호텔",
    address: "강원 속초시 조양동 청대로 105",
    region: "속초",
    facilities: { roomTypes: 3, pool: true, breakfast: true, bbq: false, pet: false, spa: true, outdoor: false },
  },
  {
    id: "acc-06",
    name: "경주 황리단길 한옥스테이",
    type: "한옥",
    address: "경북 경주시 포석로 1080-14",
    region: "경주",
    facilities: { roomTypes: 2, pool: false, breakfast: true, bbq: false, pet: false, spa: false, outdoor: true },
  },
  {
    id: "acc-07",
    name: "부산 광안리 씨사이드",
    type: "호텔",
    address: "부산 수영구 광안해변로 219",
    region: "부산",
    facilities: { roomTypes: 3, pool: false, breakfast: true, bbq: false, pet: false, spa: true, outdoor: false },
  },
  {
    id: "acc-08",
    name: "양양 서피비치 풀빌라",
    type: "풀빌라",
    address: "강원 양양군 현북면 하조대해안길 119",
    region: "양양",
    facilities: { roomTypes: 2, pool: true, breakfast: false, bbq: true, pet: true, spa: false, outdoor: true },
  },
  {
    id: "acc-09",
    name: "남해 독일마을 펜션",
    type: "펜션",
    address: "경남 남해군 삼동면 독일로 92",
    region: "남해",
    facilities: { roomTypes: 2, pool: false, breakfast: true, bbq: true, pet: false, spa: false, outdoor: true },
  },
  {
    id: "acc-10",
    name: "태안 안면도 오션리조트",
    type: "리조트",
    address: "충남 태안군 안면읍 꽃지해안로 400",
    region: "태안",
    facilities: { roomTypes: 3, pool: true, breakfast: true, bbq: true, pet: false, spa: true, outdoor: true },
  },
  {
    id: "acc-11",
    name: "제주 성산 프라이빗 독채",
    type: "독채",
    address: "제주 서귀포시 성산읍 일출로 284",
    region: "제주",
    facilities: { roomTypes: 1, pool: true, breakfast: false, bbq: true, pet: true, spa: false, outdoor: true },
  },
  {
    id: "acc-12",
    name: "평창 대관령 마운틴로지",
    type: "리조트",
    address: "강원 평창군 대관령면 올림픽로 715",
    region: "평창",
    facilities: { roomTypes: 3, pool: false, breakfast: true, bbq: true, pet: false, spa: true, outdoor: true },
  },
  {
    id: "acc-13",
    name: "통영 케이블카뷰 스테이",
    type: "펜션",
    address: "경남 통영시 발개로 205",
    region: "통영",
    facilities: { roomTypes: 2, pool: false, breakfast: false, bbq: true, pet: false, spa: false, outdoor: true },
  },
  {
    id: "acc-14",
    name: "인천 을왕리 비치호텔",
    type: "호텔",
    address: "인천 중구 왕산해안로 27",
    region: "인천",
    facilities: { roomTypes: 2, pool: true, breakfast: true, bbq: false, pet: false, spa: false, outdoor: false },
  },
];

/** 객실 타입 수 → 객실 이름. 유형 템플릿에 정의된 순서를 따른다. */
const ROOM_TYPE_NAMES = ["스탠다드룸", "디럭스룸", "스위트룸"];

/**
 * 시설 정보 → 필수 컷 목록 자동 생성.
 *
 * AI가 아니다. 이미 입력받은 데이터를 규칙으로 연결한 것뿐이다.
 * "AI 안 쓰는 자동화"의 사례로 숙소 관리 화면에서 이 함수의 결과를 실시간으로 보여준다.
 */
export function generateShotList(
  facilities: Facilities,
  accommodationId = "preview",
): ShotItem[] {
  const items: Array<Omit<ShotItem, "id" | "accommodationId">> = [];

  const push = (
    label: string,
    minCount: number,
    derivedFrom: string,
    isRequired = true,
  ) => items.push({ label, minCount, isRequired, autoGenerated: true, derivedFrom });

  push("외관", 2, "숙소 유형 템플릿 (공통)");
  push("로비 · 공용 라운지", 2, "숙소 유형 템플릿 (공통)");

  const roomCount = Math.max(1, Math.min(3, facilities.roomTypes));
  const rooms = ROOM_TYPE_NAMES.slice(0, roomCount);
  rooms.forEach((room) => push(room, 5, `객실 ${facilities.roomTypes}타입`));
  push(
    roomCount > 1 ? `욕실 ${roomCount}종` : "욕실",
    roomCount * 2,
    `객실 ${facilities.roomTypes}타입`,
  );

  if (facilities.pool) push("수영장", 3, "수영장 O");
  if (facilities.pool) push("수영장 야간", 2, "수영장 O", false);
  if (facilities.breakfast) push("조식장", 2, "조식 O");
  if (facilities.bbq) push("바비큐존", 3, "바비큐 O");
  if (facilities.spa) push("스파 · 사우나", 2, "스파 O");
  if (facilities.pet) push("반려동물 동반 공간", 2, "반려동물 O");
  if (facilities.outdoor) push("정원 · 테라스", 2, "야외 공간 O");

  push("야간 전경", 2, "숙소 유형 템플릿 (공통)", false);

  return items.map((item, i) => ({
    ...item,
    id: `${accommodationId}-shot-${String(i + 1).padStart(2, "0")}`,
    accommodationId,
  }));
}

export function getAccommodation(id: string): Accommodation | undefined {
  return ACCOMMODATIONS.find((a) => a.id === id);
}
