import type { Accommodation, FacilityDef, ShotItem } from "./types";

/**
 * 시설 마스터.
 *
 * 촬영 체크리스트는 여기서 나온다. 촬영팀이 숙소마다 목록을 새로 쓰지 않는 이유다.
 * 시설 항목의 규칙을 한 번 고치면 그 시설을 가진 모든 숙소의 체크리스트가 같이 바뀐다.
 */
export const FACILITY_DEFS: FacilityDef[] = [
  {
    id: "f-common",
    label: "공통",
    scope: "공통",
    description: "모든 숙소에 무조건 들어가는 컷. 유형과 무관하다.",
    rules: [
      { label: "외관", minCount: 2 },
      { label: "로비 · 공용 라운지", minCount: 2 },
      { label: "야간 전경", minCount: 2, optional: true },
    ],
  },
  {
    id: "f-room",
    label: "객실",
    scope: "객실",
    description:
      "숙소의 객실 타입 수만큼 반복 전개된다. 3타입이면 객실 3종 + 욕실 3종이 만들어진다.",
    rules: [
      { label: "객실", minCount: 5 },
      { label: "욕실", minCount: 2 },
    ],
  },
  {
    id: "f-pool",
    label: "수영장",
    scope: "선택",
    description: "야간 컷은 조명 세팅이 따로 필요해 권장으로 둔다.",
    rules: [
      { label: "수영장", minCount: 3 },
      { label: "수영장 야간", minCount: 2, optional: true },
    ],
  },
  {
    id: "f-breakfast",
    label: "조식",
    scope: "선택",
    description: "조식장 전경과 세팅 컷.",
    rules: [{ label: "조식장", minCount: 2 }],
  },
  {
    id: "f-bbq",
    label: "바비큐",
    scope: "선택",
    description: "누락이 가장 자주 나는 항목. 야외라 동선에서 빠지기 쉽다.",
    rules: [{ label: "바비큐존", minCount: 3 }],
  },
  {
    id: "f-spa",
    label: "스파 · 사우나",
    scope: "선택",
    description: "습기 때문에 렌즈 세팅이 달라 별도 컷으로 관리한다.",
    rules: [{ label: "스파 · 사우나", minCount: 2 }],
  },
  {
    id: "f-pet",
    label: "반려동물 동반",
    scope: "선택",
    description: "반려동물 전용 공간이 별도로 있는 경우.",
    rules: [{ label: "반려동물 전용 공간", minCount: 2 }],
  },
  {
    id: "f-outdoor",
    label: "정원 · 테라스",
    scope: "선택",
    description: "야외 공용 공간.",
    rules: [{ label: "정원 · 테라스", minCount: 2 }],
  },
];

/** 객실 타입 수 → 객실 이름. 마스터에 정의된 순서를 따른다. */
export const ROOM_TYPE_NAMES = ["스탠다드룸", "디럭스룸", "스위트룸"];

/**
 * 시설 마스터 + 숙소가 고른 항목 → 촬영 체크리스트 전개.
 *
 * AI가 아니다. 이미 입력받은 데이터를 규칙으로 연결한 것뿐이다.
 * "AI 안 쓰는 자동화"의 사례로 시설 관리 화면에서 이 함수의 결과를 실시간으로 보여준다.
 */
export function generateShotList(
  defs: FacilityDef[],
  roomTypes: number,
  facilityIds: string[],
): ShotItem[] {
  const items: Array<Omit<ShotItem, "id">> = [];
  const rooms = ROOM_TYPE_NAMES.slice(0, Math.max(1, Math.min(3, roomTypes)));

  for (const def of defs) {
    if (def.scope === "선택" && !facilityIds.includes(def.id)) continue;

    if (def.scope === "객실") {
      for (const room of rooms) {
        for (const rule of def.rules) {
          items.push({
            label: rule.label === "객실" ? room : `${room} ${rule.label}`,
            minCount: rule.minCount,
            isRequired: !rule.optional,
            autoGenerated: true,
            facilityId: def.id,
            derivedFrom: `객실 ${roomTypes}타입`,
          });
        }
      }
      continue;
    }

    for (const rule of def.rules) {
      items.push({
        label: rule.label,
        minCount: rule.minCount,
        isRequired: !rule.optional,
        autoGenerated: true,
        facilityId: def.id,
        derivedFrom: def.scope === "공통" ? "공통 (모든 숙소)" : `${def.label} 보유`,
      });
    }
  }

  return items.map((item, i) => ({
    ...item,
    id: `shot-${String(i + 1).padStart(2, "0")}`,
  }));
}

export function shotListFor(
  defs: FacilityDef[],
  acc: Accommodation,
): ShotItem[] {
  return generateShotList(defs, acc.roomTypes, acc.facilityIds);
}

/** 선택 가능한(=숙소가 체크하는) 시설 항목만 */
export function selectableFacilities(defs: FacilityDef[]): FacilityDef[] {
  return defs.filter((d) => d.scope === "선택");
}
