import type { Accommodation, FacilityDef, ShotItem } from "./types";

/**
 * 시설 마스터.
 *
 * 촬영 체크리스트는 여기서 나온다. 촬영팀이 숙소마다 목록을 새로 쓰지 않는 이유다.
 * 시설 항목의 규칙을 한 번 고치면 그 시설을 가진 모든 숙소의 체크리스트가 같이 바뀐다.
 *
 * 컷 이름은 전부 사진만 보고 판정 가능한 공간 유형이다.
 * 등급명이나 객실 번호는 쓰지 않는다. AI가 같은 숙소의 객실 두 장을 구분할 수 없어서다.
 */
export const FACILITY_DEFS: FacilityDef[] = [
  {
    id: "f-common",
    label: "공통",
    scope: "공통",
    description: "모든 숙소에 무조건 들어가는 컷.",
    rules: [
      { label: "외관", minCount: 2 },
      { label: "로비 · 공용 라운지", minCount: 2 },
      { label: "야간 전경", minCount: 2, optional: true },
    ],
  },
  {
    id: "f-room",
    label: "객실",
    scope: "객실",
    description:
      "객실 1개당 필요한 컷 수. 숙소의 객실 수를 곱합니다. 객실 2개면 객실 10컷.",
    rules: [
      { label: "객실", minCount: 5 },
      { label: "욕실", minCount: 2 },
    ],
  },
  {
    id: "f-pool",
    label: "수영장",
    scope: "선택",
    description: "야간 컷은 조명 세팅이 따로 필요해 권장으로 둔다.",
    rules: [
      { label: "수영장", minCount: 3 },
      { label: "수영장 야간", minCount: 2, optional: true },
    ],
  },
  {
    id: "f-breakfast",
    label: "조식",
    scope: "선택",
    description: "조식장 전경과 세팅 컷.",
    rules: [{ label: "조식장", minCount: 2 }],
  },
  {
    id: "f-bbq",
    label: "바비큐",
    scope: "선택",
    description: "누락이 가장 자주 나는 항목. 야외라 동선에서 빠지기 쉽다.",
    rules: [{ label: "바비큐존", minCount: 3 }],
  },
  {
    id: "f-spa",
    label: "스파 · 사우나",
    scope: "선택",
    description: "습기 때문에 렌즈 세팅이 달라 별도 컷으로 관리한다.",
    rules: [{ label: "스파 · 사우나", minCount: 2 }],
  },
  {
    id: "f-pet",
    label: "반려동물 동반",
    scope: "선택",
    description: "반려동물 전용 공간이 별도로 있는 경우.",
    rules: [{ label: "반려동물 전용 공간", minCount: 2 }],
  },
  {
    id: "f-outdoor",
    label: "정원 · 테라스",
    scope: "선택",
    description: "야외 공용 공간.",
    rules: [{ label: "정원 · 테라스", minCount: 2 }],
  },
];

/**
 * 시설 마스터 + 숙소가 고른 항목 → 촬영 체크리스트 전개.
 *
 * 객실 규칙만 객실 수를 곱한다. 객실 2개면 객실 10컷, 욕실 4컷.
 */
export function generateShotList(
  defs: FacilityDef[],
  roomCount: number,
  facilityIds: string[],
): ShotItem[] {
  const rooms = Math.max(1, roomCount);
  const items: Array<Omit<ShotItem, "id">> = [];

  for (const def of defs) {
    if (def.scope === "선택" && !facilityIds.includes(def.id)) continue;

    const isRoom = def.scope === "객실";
    for (const rule of def.rules) {
      items.push({
        label: rule.label,
        minCount: isRoom ? rule.minCount * rooms : rule.minCount,
        isRequired: !rule.optional,
        autoGenerated: true,
        facilityId: def.id,
        derivedFrom: isRoom
          ? `객실 ${rooms}개 × ${rule.minCount}컷`
          : def.scope === "공통"
            ? "공통 (모든 숙소)"
            : `${def.label} 보유`,
      });
    }
  }

  return items.map((item, i) => ({
    ...item,
    id: `shot-${String(i + 1).padStart(2, "0")}`,
  }));
}

export function shotListFor(defs: FacilityDef[], acc: Accommodation): ShotItem[] {
  return generateShotList(defs, acc.roomCount, acc.facilityIds);
}
