/**
 * 목업이지만 실제 DB 스키마와 형태를 맞춘다.
 * 나중에 백엔드를 붙이면 이 타입이 그대로 API 응답 타입이 된다.
 */

export type ContentStatus =
  | "촬영예정"
  | "촬영완료"
  | "보정중"
  | "검수"
  | "발행";

export const CONTENT_STATUSES: ContentStatus[] = [
  "촬영예정",
  "촬영완료",
  "보정중",
  "검수",
  "발행",
];

export type AccommodationType =
  | "풀빌라"
  | "독채"
  | "호텔"
  | "펜션"
  | "글램핑"
  | "한옥"
  | "리조트";

export interface Facilities {
  /** 객실 타입 수 */
  roomTypes: number;
  pool: boolean;
  breakfast: boolean;
  bbq: boolean;
  pet: boolean;
  spa: boolean;
  /** 야외 정원/테라스 */
  outdoor: boolean;
}

export interface Accommodation {
  id: string;
  name: string;
  type: AccommodationType;
  address: string;
  region: string;
  facilities: Facilities;
}

/** 필수 컷 정의. 숙소 유형 템플릿 + 시설 정보에서 자동 생성된다. */
export interface ShotItem {
  id: string;
  accommodationId: string;
  label: string;
  minCount: number;
  isRequired: boolean;
  autoGenerated: boolean;
  /** 어떤 시설 정보에서 파생됐는지 (자동 생성 근거 표시용) */
  derivedFrom: string;
}

export interface Content {
  id: string;
  accommodationId: string;
  shootDate: string;
  photographer: string;
  retoucher: string | null;
  status: ContentStatus;
  statusChangedAt: string;
  stuckDays: number;
  reshootCount: number;
  /** 현장 모드로 촬영했는지 */
  fieldMode: boolean;
}

export type ApprovalStatus = "승인" | "반려" | "대기";

export interface RejectRecord {
  round: number;
  at: string;
  by: string;
  reason: string;
}

/** AI 1차 검수 플래그 */
export type ReviewFlag = "수평 틀어짐" | "노출 편차" | "색온도 편차" | "눈감음";

/** AI 셀렉에서 제외된 사유 */
export type ExcludeReason = "흔들림" | "중복" | "노출 오류" | null;

export interface Photo {
  id: string;
  contentId: string;
  previewUrl: string;
  thumbUrl: string;
  rawPath: string;
  aiLabel: string;
  confidence: number;
  selected: boolean;
  excludeReason: ExcludeReason;
  reviewFlags: ReviewFlag[];
  approvalStatus: ApprovalStatus;
  rejectHistory: RejectRecord[];
  /** 보정 톤 일관성 검사용 측정값 */
  colorTempK: number;
  brightness: number;
  retoucher: string | null;
}

export type PublishMode = "자동 발행" | "심사 필요" | "수동 발행";

export interface ChannelProfile {
  id: string;
  name: string;
  ratio: string;
  ratioValue: number;
  maxPhotos: number;
  tone: string;
  publishMode: PublishMode;
  /** 발행 방식 근거 (실제 API 정책 조사 결과) */
  apiNote: string;
}
