/**
 * 목업이지만 실제 DB 스키마와 형태를 맞춘다.
 * 나중에 백엔드를 붙이면 이 타입이 그대로 API 응답 타입이 된다.
 */

export type ContentStatus =
  | "촬영예정"
  | "촬영완료"
  | "보정중"
  | "검수"
  | "발행";

export const CONTENT_STATUSES: ContentStatus[] = [
  "촬영예정",
  "촬영완료",
  "보정중",
  "검수",
  "발행",
];

export type AccommodationType =
  | "풀빌라"
  | "독채"
  | "호텔"
  | "펜션"
  | "글램핑"
  | "한옥"
  | "리조트";

/* ------------------------------------------------------------------ *
 * 시설 마스터
 *
 * 촬영 필수 컷이 어디서 나오는지의 원천.
 * 시설 항목 하나가 "이 시설이 있으면 이런 컷이 몇 장 필요하다"는 규칙을 갖는다.
 * 숙소는 이 항목들을 고르기만 하고, 체크리스트는 규칙에서 전개된다.
 * ------------------------------------------------------------------ */

export interface ShotRule {
  label: string;
  minCount: number;
  /** 권장 컷. 없어도 촬영 완료로 본다 */
  optional?: boolean;
}

export type FacilityScope = "공통" | "객실" | "선택";

export interface FacilityDef {
  id: string;
  label: string;
  /**
   * 공통 — 모든 숙소에 무조건 적용
   * 객실 — 숙소의 객실 타입 수만큼 반복 전개
   * 선택 — 숙소가 보유를 체크했을 때만 적용
   */
  scope: FacilityScope;
  rules: ShotRule[];
  description: string;
}

export interface Accommodation {
  id: string;
  name: string;
  type: AccommodationType;
  address: string;
  region: string;
  /** 객실 타입 수. 객실 규칙이 이 수만큼 전개된다 */
  roomTypes: number;
  /** 보유한 시설 항목 (FacilityDef.id) */
  facilityIds: string[];
}

/** 시설 마스터에서 전개된 촬영 체크리스트 한 줄 */
export interface ShotItem {
  id: string;
  /**
   * 컷 이름. 사진만 보고 판정 가능한 공간 유형이어야 한다.
   * 등급명이나 객실 번호는 여기 들어갈 수 없다. 이미지에 근거가 없기 때문이다.
   */
  label: string;
  minCount: number;
  isRequired: boolean;
  autoGenerated: boolean;
  /** 어느 시설 항목에서 나왔는지 (자동 생성 근거 표시용) */
  facilityId: string;
  derivedFrom: string;
}

export interface Content {
  id: string;
  accommodationId: string;
  shootDate: string;
  photographer: string;
  retoucher: string | null;
  status: ContentStatus;
  statusChangedAt: string;
  stuckDays: number;
  reshootCount: number;
  /** 현장 모드로 촬영했는지 */
  fieldMode: boolean;
}

export type ApprovalStatus = "승인" | "반려" | "대기";

export interface RejectRecord {
  round: number;
  at: string;
  by: string;
  reason: string;
}

/** AI 1차 검수 플래그 */
export type ReviewFlag = "수평 틀어짐" | "노출 편차" | "색온도 편차" | "눈감음";

/** AI 셀렉에서 제외된 사유 */
export type ExcludeReason = "흔들림" | "중복" | "노출 오류" | null;

export interface Photo {
  id: string;
  contentId: string;
  previewUrl: string;
  thumbUrl: string;
  rawPath: string;
  /** AI가 판정한 공간 유형 */
  aiLabel: string;
  confidence: number;
  selected: boolean;
  excludeReason: ExcludeReason;
  reviewFlags: ReviewFlag[];
  approvalStatus: ApprovalStatus;
  rejectHistory: RejectRecord[];
  /** 보정 톤 일관성 검사용 측정값 */
  colorTempK: number;
  brightness: number;
  retoucher: string | null;
}

export type PublishMode = "자동 발행" | "심사 필요" | "수동 발행";

export interface ChannelProfile {
  id: string;
  name: string;
  ratio: string;
  maxPhotos: number;
  tone: string;
  publishMode: PublishMode;
  /** 발행 방식 근거 (실제 API 정책 조사 결과) */
  apiNote: string;
}
